### ISSUE TITLE
Latest master fails with submissions that contain non-ascii values

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobocat#401]
I realize it's work in progress, but just wanted to let you know that the XML hashing in kobocat based on the current master branch fails when a submission contains non-unicode values.

The reason is this: https://github.com/kobotoolbox/kobocat/commit/aa7ceec9b90b6bd02db1abce3895e8249ca84881#diff-cd70edf722f36980f7141cc888aacf8fL309

It seems that `input_string` is already a `str` here, so the `encode` method will try to decode it which will fail if it contains non-ascii characters.

**Comment by jnm** [comment]
Thanks for the report! Committing a fix for this now.

**Comment by jnm** [comment]
Deploying this revealed some more nuance:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 442: ordinal not in range(128)
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "onadata/apps/main/views.py", line 1233, in delete_data
    Instance.set_deleted_at(data_id)
  File "onadata/apps/logger/models/instance.py", line 161, in set_deleted_at
    instance.set_deleted(deleted_at)
  File "onadata/apps/logger/models/instance.py", line 377, in set_deleted
    self.save()
  File "onadata/apps/logger/models/instance.py", line 367, in save
    self._populate_xml_hash()
  File "onadata/apps/logger/models/instance.py", line 230, in _populate_xml_hash
    self.xml_hash = self.get_hash(self.xml)
  File "onadata/apps/logger/models/instance.py", line 346, in get_hash
    return sha256(input_string).hexdigest()
```
So... the instance somehow got an `xml_hash` on submission, but trying to recalculate it fails?
```
In [22]: i = Instance.objects.get(id=8226908)

In [23]: i.xml_hash
Out[23]: u'b4c8bd5912e5cc3208defa722d1e621430d4fbbd3dbe84ab29a1396dc0c0753a'

In [24]: i.get_hash(i.xml)
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-24-dcd2865c60da> in <module>()
----> 1 i.get_hash(i.xml)

/home/ubuntu/src/kobocat/onadata/apps/logger/models/instance.pyc in get_hash(input_string)
    344         :rtype: str
    345         '''
--> 346         return sha256(input_string).hexdigest()
    347 
    348     @property

UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 398: ordinal not in range(128)
```
My theory is that `xml` is a `str` when it's first submitted, but when reading it back from Postgres, it's a `unicode`:
```
In [25]: type(i.xml)
Out[25]: unicode

In [26]: i.get_hash(i.xml.encode('utf-8'))
Out[26]: 'b4c8bd5912e5cc3208defa722d1e621430d4fbbd3dbe84ab29a1396dc0c0753a'
```
