### ISSUE TITLE
Deleting a repeat breaks parsing of existing submissions

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobocat#426]
Steps to reproduce:

*   create a simple form with a repeating group
*   create at least one submission
*   change the group to not repeat and redeploy

If you now try to view the submission table or trigger a management command like `remongo` that processes the form, you will get something like the traceback pasted below. In the case of e.g. `remongo`, the command will crash and subsequent forms will not be processed.

```
Traceback (most recent call last):
  File "/usr/src/app/onadata/apps/logger/xform_instance_parser.py", line 277, in __init__
    self.parse(xml_str)
  File "/usr/src/app/onadata/apps/logger/xform_instance_parser.py", line 288, in parse
    self._dict = _xml_node_to_dict(self._root_node, repeats)
  File "/usr/src/app/onadata/apps/logger/xform_instance_parser.py", line 171, in _xml_node_to_dict
    u" while not a repeat" % child_name))
InstanceMultipleNodeError: Multiple nodes with the same name 'group_bn7wu23' while not a repeat
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/onadata/apps/viewer/management/commands/remongo.py", line 50, in handle
    pi.update_mongo(async=False)
  File "/usr/src/app/onadata/apps/viewer/models/parsed_instance.py", line 270, in update_mongo
    d = self.to_dict_for_mongo()
  File "/usr/src/app/onadata/apps/viewer/models/parsed_instance.py", line 243, in to_dict_for_mongo
    d = self.to_dict()
  File "/usr/src/app/onadata/apps/viewer/models/parsed_instance.py", line 278, in to_dict
    self._dict_cache = self.instance.get_dict()
  File "/usr/src/app/onadata/apps/logger/models/instance.py", line 214, in get_dict
    return self._parser.get_flat_dict_with_attributes() if flat else\
  File "/usr/src/app/onadata/apps/logger/xform_instance_parser.py", line 335, in get_flat_dict_with_attributes
    result = self.to_flat_dict().copy()
  File "/usr/src/app/onadata/apps/logger/xform_instance_parser.py", line 309, in to_flat_dict
    return self._flat_dict
AttributeError: 'XFormInstanceParser' object has no attribute '_flat_dict'
```

**Comment by jeverling** [comment]
This not only affects `sync_mongo` management command, but users will also get a `500` error when trying to display the table of submissions.

**Comment by jeverling** [comment]
Thanks for fixing this!
