### ISSUE TITLE
ODK Briefcase internal server error downloading encrypted KC submission with multiple photos

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/kobocat#483]
Not 100% sure if this a Briefcase or KoBoCAT or Enketo issue. I'm trying to download 1 encrypted submission (with 2 photos) in ODK Briefcase 1.12.1 and see this error in briefcase.log:

```
Caused by: org.opendatakit.briefcase.util.ServerFetcher$SubmissionDownloadException: Fetch of a submission failed.  Detailed error: INTERNAL SERVER ERROR (500) while accessing: https://kc.kobotoolbox.org/martijnr/view/downloadSubmission?formId=a5Z4d9Cdw2fmMicd2w6a7U%5B%40version%3DvgvTG5mj9iUEuXVcpPpea3+and+%40uiVersion%3Dnull%5D%2Fdata%5B%40key%3Duuid%3Ac384191d-f744-4211-85b7-73db833719cd%5D
Please verify that the URL, your user credentials and your permissions are all correct.
	at org.opendatakit.briefcase.util.ServerFetcher.downloadSubmission(ServerFetcher.java:457)
	at org.opendatakit.briefcase.util.ServerFetcher.access$300(ServerFetcher.java:61)
	at org.opendatakit.briefcase.util.ServerFetcher$SubmissionDownload.call(ServerFetcher.java:406)
	at org.opendatakit.briefcase.util.ServerFetcher$SubmissionDownload.call(ServerFetcher.java:388)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 common frames omitted
```

It looks like a KC error.

I have no problem downloading non-encrypted submissions for other forms from the same KC account with the same credentials. I have the feeling this relates to multiple photos in one record (though not all of such records fail in another encrypted test form). The form ID is "a5Z4d9Cdw2fmMicd2w6a7U". It's in kc.kobotoolbox.org/martijnr.
I experience no such issue with the same form on ODK Aggregate.

**Comment by jnm** [comment]
@noliveleger, I don't think you'll have to get into the mucky bits of encrypted forms, because it looks like a simple(?!) Django mistake:
```
MultipleObjectsReturned: get() returned more than one Instance -- it returned 2!
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "onadata/apps/api/viewsets/briefcase_api.py", line 217, in retrieve
    self.object = self.get_object()
  File "onadata/apps/api/viewsets/briefcase_api.py", line 111, in get_object
    uuid=uuid)
  File "rest_framework/generics.py", line 20, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "django/shortcuts.py", line 155, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
```
https://sentry.kbtdev.org/kobo/kobocat/issues/743/?query=is:unresolved%20user.username:martijnr

**Comment by noliveleger** [comment]
@jnm, You are right. Submissions in database are duplicated.
