### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 245: ordinal not in range(128)

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobocat#545]
when a xform is deployed from kpi I got an exception.
Can this be safe handle from code level or there is nothing to worry form users and devops point of view

`Internal Server Error: /api/v1/forms/1257
Traceback (most recent call last):
File "/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/kobocat/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/kobocat/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
return self.dispatch(request, *args, **kwargs)
File "/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
response = self.handle_exception(exc)
File "/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
response = handler(request, *args, **kwargs)
File "/kobocat/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 78, in partial_update
return self.update(request, *args, **kwargs)
File "./onadata/apps/api/viewsets/xform_viewset.py", line 800, in update
survey = utils.publish_xlsform(request, owner, existing_xform)
File "./onadata/apps/api/tools.py", line 264, in publish_xlsform
return publish_form(set_form)
File "./onadata/libs/utils/logger_tools.py", line 413, in publish_form
if u"ODK Validate Errors" not in e.message:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 245: ordinal not in range(128)`

From source 
`https://github.com/kobotoolbox/kobocat/blob/master/onadata/libs/utils/logger_tools.py
except Exception as e:
        # TODO: Something less horrible. This masks storage backend
        # `ImportError`s and who knows what else

        # ODK validation errors are vanilla errors and it masks a lot of regular
        # errors if we try to catch it so let's catch it, BUT reraise it
        # if we don't see typical ODK validation error messages in it.
        if u"ODK Validate Errors" not in e.message:
            raise

        # error in the XLS file; show an error to the user
        return {
            'type': 'alert-error',
            'text': unicode(e)
        }`

**Comment by jnm** [comment]
Could you share the XLS file with us, or is it private?

**Comment by awemulya** [comment]
I have requested approval to share the invalid file to my higher authorities. will respond asap
 the e.message value is
   ` "ODK Validate Errors:\n>> XForm is invalid. See above for the errors.\norg.javarosa.xform.parse.XFormParseException: Encountered a problem with display condition for node [${group_vm5vr00}] at line:  ${Functional_electricity}  = 'No' OR 'N/A', Couldn't understand the expression starting at this point: ...ricity  = 'No'\xcd\x8eOR 'N/A'\n\nResult: Invalid"`

and `u"ODK Validate Errors" not in e.message` raises 
`unicode(e.message)` raises 

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 317: ordinal not in range(128)
`

**Comment by jnm** [comment]
OK, I think I understand. The problem is that
1. There's an error in the XLSForm syntax (`${Functional_electricity} = 'No' OR 'N/A'`);
2. ODK Validate includes a `cd8e` character sequence, [`COMBINING UPWARDS ARROW BELOW`](https://www.fileformat.info/info/unicode/char/034e/index.htm), in the error message to point at the bad expression;
3. KoBoCAT can't handle this Unicode character sequence, causing `UnicodeDecodeError` to be raised.

**Comment by awemulya** [comment]
Thank You @jnm  for the details. Will look if the error details could be displayed instread of raise

**Comment by jnm** [comment]
Link to `publish_form()`, which is blowing up somewhere: https://github.com/kobotoolbox/kobocat/blob/33b4c6a93aad0c42ab2fb42dcbd109ea5882c3b2/onadata/libs/utils/logger_tools.py#L453-L498

**Comment by jnm** [comment]
@duvld discovered the source of the problem:
https://github.com/kobotoolbox/kobocat/blob/33b4c6a93aad0c42ab2fb42dcbd109ea5882c3b2/onadata/libs/utils/logger_tools.py#L491
I'm guessing that `e.message` contains UTF-8 but is a `str` instead of a `unicode`, e.g.:
```
john@scrappy:~$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> err_str = "at this point: ...ricity = 'No'\xcd\x8eOR 'N/A'"
>>> 'str' in err_str
False
>>> u'unicode' in err_str  # coerces err_str to unicode?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 31: ordinal not in range(128)
>>> unicode(err_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 31: ordinal not in range(128)
>>> err_str.decode('utf-8')
u"at this point: ...ricity = 'No'\u034eOR 'N/A'"
>>> u'unicode' in err_str.decode('utf-8')
False
>>> u'at this point' in err_str.decode('utf-8')
True
```

## A better way
Thanks to @dorey [(5 years ago?)](https://github.com/XLSForm/pyxform/commit/a421774ed58a0595861a211e0bee7d2121cbba2a) we can trash the whole `except Exception as e…if u"ODK Validate Errors" not in e.message` nastiness altogether. Also, v1.0.0+ of pyxform deals with unicode better in these ODK Validate messages: https://github.com/XLSForm/pyxform/commit/ce94da4321a3c868cefaf9d5b5528ea822321e80#diff-ecafa3247a1ef53d5abd7c60ee989681L111-L115

**Comment by jnm** [comment]
Blocked by https://github.com/kobotoolbox/kobocat/issues/604
