### ISSUE TITLE
xform title regex can't deal with HTML

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobocat#697]
```
Traceback (most recent call last):
  File "<console>", line 8, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 537, in delete
    collector.delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 314, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/src/kobocat/onadata/apps/logger/models/instance.py", line 103, in update_xform_submission_count_delete
    xform.save(update_fields=['num_of_submissions'])
  File "/srv/src/kobocat/onadata/apps/logger/models/xform.py", line 191, in save
    self._set_title()
  File "/srv/src/kobocat/onadata/apps/logger/models/xform.py", line 162, in _set_title
    title_xml = matches[0][:XFORM_TITLE_LENGTH]
IndexError: list index out of range
```

OK, here's why this is broken. The form has:
```xml
<h:title><span style="color:red; font-family:gill sans">Weightlifting Wales #FindYourStrength</span></h:title>
```
but KoBoCAT assumes:
```python
title_pattern = re.compile(r"<h:title>([^<]+)</h:title>")
```

Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Ending.20use.20of.20.60_deleted_at.60/near/23293

**Comment by jnm** [comment]
Affected `Instance` PKs on HHI:
```
[1507561, 1546527, 1738143, 1754050, 1754077, 1754080, 1754097, 1754101, 1754146, 1754150, 1754162, 1756004, 1768696]
```
